name: Deploy Next.js App to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # specify your self-hosted runner label here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # adjust Node.js version as needed

      - name: Create .env file
        run: |
            touch .env
            echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Install dependencies
        run: |
          npm install

      - name: Build Next.js application
        run: |
          npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-app
          path: .next
